[package]
name = "functions"
version = "0.1.0"
authors = ["gravity34 <16541089@firat.edu.tr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
